# Generated by Django 4.2.10 on 2026-06-19 13:48

from django.db import migrations, models
import django.db.models.deletion
import tickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='票种名称')),
                ('ticket_type', models.CharField(choices=[('single_day', '单日票'), ('multi_day', '通票'), ('vip', 'VIP票'), ('exhibitor', '参展商证'), ('media', '媒体证'), ('staff', '工作人员证')], default='single_day', max_length=20, verbose_name='票类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='票种说明')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='票价')),
                ('quantity', models.IntegerField(default=0, verbose_name='总票量（0为不限量）')),
                ('sold_count', models.IntegerField(default=0, verbose_name='已售数量')),
                ('max_per_order', models.IntegerField(default=5, verbose_name='单账号限购')),
                ('on_sale', models.BooleanField(default=True, verbose_name='是否在售')),
                ('sale_start_time', models.DateTimeField(blank=True, null=True, verbose_name='开售时间')),
                ('sale_end_time', models.DateTimeField(blank=True, null=True, verbose_name='停售时间')),
                ('valid_date', models.DateField(blank=True, null=True, verbose_name='有效日期（单日票）')),
                ('refund_policy', models.CharField(choices=[('no_refund', '不退不换'), ('full_refund', '全额退款'), ('partial_refund', '部分退款')], default='no_refund', max_length=20, verbose_name='退票政策')),
                ('refund_deadline', models.DateTimeField(blank=True, null=True, verbose_name='退票截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tiers', to='exhibitions.exhibition', verbose_name='所属展会')),
            ],
            options={
                'verbose_name': '票档配置',
                'verbose_name_plural': '票档配置',
                'db_table': 'cf_ticket_tiers',
                'ordering': ['exhibition', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(default=tickets.models._generate_ticket_no, max_length=32, unique=True, verbose_name='票号')),
                ('ticket_type', models.CharField(choices=[('single_day', '单日票'), ('multi_day', '通票'), ('vip', 'VIP票'), ('exhibitor', '参展商证'), ('media', '媒体证'), ('staff', '工作人员证')], max_length=20, verbose_name='票类型')),
                ('ticket_code', models.CharField(default=tickets.models._generate_ticket_code, max_length=64, unique=True, verbose_name='入场核验码')),
                ('status', models.CharField(choices=[('unpaid', '待支付'), ('paid', '已支付'), ('used', '已使用'), ('refunded', '已退票'), ('cancelled', '已取消'), ('expired', '已过期')], default='unpaid', max_length=20, verbose_name='票状态')),
                ('holder_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='持票人姓名')),
                ('holder_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='持票人电话')),
                ('holder_id_card', models.CharField(blank=True, max_length=30, null=True, verbose_name='身份证号')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实际支付金额')),
                ('payment_method', models.CharField(blank=True, choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('bank', '银行转账'), ('cash', '现场支付')], max_length=20, null=True, verbose_name='支付方式')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('payment_transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='支付交易号')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='退票时间')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='退款金额')),
                ('refund_reason', models.TextField(blank=True, null=True, verbose_name='退票原因')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='有效开始日期')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='有效结束日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='exhibitions.exhibition', verbose_name='所属展会')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.tickettier', verbose_name='票档')),
            ],
            options={
                'verbose_name': '门票',
                'verbose_name_plural': '门票',
                'db_table': 'cf_tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
