# Generated by Django 4.2.10 on 2026-06-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoothApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_count', models.IntegerField(default=1, verbose_name='申请展位数量')),
                ('club_name', models.CharField(max_length=200, verbose_name='社团/摊位名称')),
                ('club_introduction', models.TextField(blank=True, null=True, verbose_name='社团简介')),
                ('works_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='参展作品类型')),
                ('main_works', models.TextField(blank=True, null=True, verbose_name='主要作品介绍')),
                ('contact_name', models.CharField(max_length=50, verbose_name='联系人姓名')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='联系邮箱')),
                ('social_media', models.CharField(blank=True, max_length=500, null=True, verbose_name='社交媒体账号')),
                ('has_power', models.BooleanField(default=False, verbose_name='是否需要额外用电')),
                ('power_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='用电需求说明')),
                ('special_requirements', models.TextField(blank=True, null=True, verbose_name='特殊需求')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '审核通过(待缴费)'), ('rejected', '审核驳回'), ('paid', '已缴费'), ('cancelled', '已取消'), ('checked_in', '已签到入场'), ('completed', '已完成')], default='draft', max_length=20, verbose_name='申请状态')),
                ('review_notes', models.TextField(blank=True, null=True, verbose_name='审核备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='应缴费用')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实缴费用')),
                ('payment_method', models.CharField(blank=True, choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('bank', '银行转账'), ('cash', '现场支付')], max_length=20, null=True, verbose_name='支付方式')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('payment_transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='支付交易号')),
                ('check_in_code', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='签到核验码')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '摊位申请',
                'verbose_name_plural': '摊位申请',
                'db_table': 'cf_booth_applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
