# Generated by Django 4.2.10 on 2026-06-19 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('exhibitions', '0001_initial'),
        ('booths', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boothapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booth_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AddField(
            model_name='boothapplication',
            name='booth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='booths.booth', verbose_name='分配展位'),
        ),
        migrations.AddField(
            model_name='boothapplication',
            name='booths',
            field=models.ManyToManyField(blank=True, related_name='multi_applications', to='booths.booth', verbose_name='分配展位(多)'),
        ),
        migrations.AddField(
            model_name='boothapplication',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_applications', to=settings.AUTH_USER_MODEL, verbose_name='签到核验人'),
        ),
        migrations.AddField(
            model_name='boothapplication',
            name='exhibition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='exhibitions.exhibition', verbose_name='所属展会'),
        ),
        migrations.AddField(
            model_name='boothapplication',
            name='preferred_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_applications', to='booths.boothzone', verbose_name='意向展区'),
        ),
        migrations.AddField(
            model_name='boothapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
    ]
