# Generated by Django 4.2.10 on 2026-06-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='通道名称')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='通道位置')),
                ('gate_type', models.CharField(choices=[('ticket', '观众门票'), ('exhibitor', '摊主凭证'), ('staff', '工作人员'), ('media', '媒体'), ('vip', 'VIP通道')], default='ticket', max_length=20, verbose_name='通道类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_gates', to='exhibitions.exhibition', verbose_name='所属展会')),
            ],
            options={
                'verbose_name': '签到通道',
                'verbose_name_plural': '签到通道',
                'db_table': 'cf_checkin_gates',
                'ordering': ['exhibition', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_type', models.CharField(choices=[('ticket', '观众门票'), ('exhibitor', '摊主凭证'), ('staff', '工作人员'), ('media', '媒体'), ('vip', 'VIP通道')], max_length=20, verbose_name='签到类型')),
                ('status', models.CharField(choices=[('success', '核验通过'), ('already_checked', '重复签到'), ('invalid_code', '凭证无效'), ('expired', '凭证过期'), ('not_paid', '未支付')], default='success', max_length=30, verbose_name='核验状态')),
                ('code_used', models.CharField(blank=True, max_length=64, null=True, verbose_name='使用的核验码')),
                ('ticket_id', models.IntegerField(blank=True, null=True, verbose_name='关联门票ID')),
                ('application_id', models.IntegerField(blank=True, null=True, verbose_name='关联摊位申请ID')),
                ('person_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='人员姓名')),
                ('person_info', models.JSONField(blank=True, default=dict, verbose_name='人员附加信息')),
                ('checkin_time', models.DateTimeField(auto_now_add=True, verbose_name='签到时间')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='exhibitions.exhibition', verbose_name='所属展会')),
                ('gate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='checkins.checkingate', verbose_name='签到通道')),
            ],
            options={
                'verbose_name': '签到记录',
                'verbose_name_plural': '签到记录',
                'db_table': 'cf_checkins',
                'ordering': ['-checkin_time'],
            },
        ),
    ]
