# Generated by Django 4.2.10 on 2026-06-19 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_checkins', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['exhibition', 'checkin_time'], name='cf_checkins_exhibit_57fb5b_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['code_used'], name='cf_checkins_code_us_0ae0f7_idx'),
        ),
    ]
