# Generated by Django 4.2.10 on 2026-06-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoothZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='展区名称')),
                ('zone_type', models.CharField(choices=[('general', '普通展区'), ('premium', '精品展区'), ('cosplay', 'Cosplay专区'), ('food', '餐饮区'), ('activity', '活动舞台')], default='general', max_length=20, verbose_name='展区类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='展区说明')),
                ('color', models.CharField(default='#409EFF', max_length=20, verbose_name='标识颜色')),
                ('position_x', models.IntegerField(default=0, verbose_name='平面图X坐标')),
                ('position_y', models.IntegerField(default=0, verbose_name='平面图Y坐标')),
                ('width', models.IntegerField(default=100, verbose_name='展区宽度')),
                ('height', models.IntegerField(default=100, verbose_name='展区高度')),
                ('booth_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单个展位价格')),
                ('booth_width_meters', models.FloatField(default=1.5, verbose_name='展位宽度(米)')),
                ('booth_depth_meters', models.FloatField(default=1.5, verbose_name='展位进深(米)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='exhibitions.exhibition', verbose_name='所属展会')),
            ],
            options={
                'verbose_name': '展区',
                'verbose_name_plural': '展区',
                'db_table': 'cf_booth_zones',
                'ordering': ['exhibition', 'position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_code', models.CharField(max_length=50, verbose_name='展位编号')),
                ('status', models.CharField(choices=[('available', '可申请'), ('reserved', '已预留'), ('occupied', '已分配'), ('maintenance', '维护中')], default='available', max_length=20, verbose_name='展位状态')),
                ('grid_x', models.IntegerField(default=0, verbose_name='网格X坐标')),
                ('grid_y', models.IntegerField(default=0, verbose_name='网格Y坐标')),
                ('width_units', models.IntegerField(default=1, verbose_name='占用宽度(单位格)')),
                ('height_units', models.IntegerField(default=1, verbose_name='占用高度(单位格)')),
                ('has_electricity', models.BooleanField(default=True, verbose_name='是否有电')),
                ('has_table', models.BooleanField(default=True, verbose_name='是否有桌子')),
                ('has_chair', models.BooleanField(default=True, verbose_name='是否有椅子')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booths', to='booths.boothzone', verbose_name='所属展区')),
            ],
            options={
                'verbose_name': '展位',
                'verbose_name_plural': '展位',
                'db_table': 'cf_booths',
                'ordering': ['zone', 'grid_y', 'grid_x'],
                'unique_together': {('zone', 'booth_code')},
            },
        ),
    ]
