# Generated by Django 4.2.10 on 2026-06-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='展会名称')),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='副标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='展会介绍')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='exhibitions/', verbose_name='封面图')),
                ('venue', models.CharField(max_length=200, verbose_name='举办地点')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='详细地址')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('open_time', models.TimeField(default='09:00', verbose_name='开放时间')),
                ('close_time', models.TimeField(default='17:00', verbose_name='闭馆时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('ongoing', '进行中'), ('ended', '已结束'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('organizer_contact', models.CharField(blank=True, max_length=200, null=True, verbose_name='主办方联系方式')),
                ('max_visitors', models.IntegerField(default=5000, verbose_name='最大观众人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '展会',
                'verbose_name_plural': '展会',
                'db_table': 'cf_exhibitions',
                'ordering': ['-start_date'],
            },
        ),
    ]
